Activos-PrestamosOET/Controllers/PRESTAMOesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Activos_PrestamosOET.Models;
using System.Data;
using System.Web.UI.WebControls;
using System;
using PagedList;
using System.Globalization;
using System.Collections.Generic;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.html.simpleparser;
using System.Web;
using System.IO;
using System.Net.Http;
using System.Net.Mail;
using Newtonsoft.Json.Linq;
using SendGrid;
using System.Configuration;
using System.Diagnostics;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using Microsoft.AspNet.Identity;

namespace Activos_PrestamosOET.Controllers
{

    public class PRESTAMOesController : Controller
    {
        private PrestamosEntities db = new PrestamosEntities();

        protected static int consecutivo;
        protected String generarID()
        {
            consecutivo = (consecutivo + 1) % 999;
            return ""
            + DateTime.Now.Day.ToString("D2")
            + DateTime.Now.Month.ToString("D2")
            + DateTime.Now.Year.ToString()
            + DateTime.Now.Hour.ToString("D2")
            + DateTime.Now.Minute.ToString("D2")
            + DateTime.Now.Second.ToString("D2")
            + DateTime.Now.Millisecond.ToString("D3")
            + consecutivo.ToString("D3");
        }


        //Requiere: el id del prestamo, categoría y número de boleta del préstamo
        //Modifica: Se encarga de recuperar de la tabla de transacciones las observaciones efectuadas para cada activo devuelto de ese préstamo 
        //Regresa: la lista de observaciones de devolución de cada activo de la categoría especificada del préstamo especificado
        public List<String> traerObservaciones(String id, int cat, long? boleta)
        {
            List<String> observaciones = new List<String>();

            //obtiene todos los activos del préstamo
            var activos = db.PRESTAMOS.Include(i => i.ACTIVOes).SingleOrDefault(h => h.ID == id);
            //obtiene el id de todos los activos que pertenecen a la categoría específica
            var act = from a in activos.ACTIVOes.Where(i => i.TIPO_ACTIVOID == cat)
                      select new
                      {
                          ID = a.ID,
                      };

            //Recorre los ids y recupera la observación que se hizo al devolverlos, si es que han sido devueltos
            //de lo contrario no debería encontrar ninguna observación sino que debería obtener la hilera ""
            foreach (var i in act)
            {
                var observacion = from t in db.TRANSACCIONES
                                  where t.ACTIVOID == i.ID && t.ESTADO == "Devuelto de préstamo" && t.NUMERO_BOLETA == boleta
                                  select t.OBSERVACIONES_RECIBO;

                //si consulta observación devuelve nulo es que aún no ha habido transacciones de devolución con ese
                //activo por lo que la hilera deberá ser ""
                if (observacion == null || observacion.Count() == 0)
                {
                    observaciones.Add("");
                }
                else
                {   //En caso de si lograr recuperar algo pasan 2 casos
                    foreach (var o in observacion)
                    {
                        //El caso de que si encuentre una observación por lo que la agregará a lista de observaciones
                        //de esa categoría de activo
                        if (o != null)
                            observaciones.Add(o.ToString());
                        else //en caso de que observacion recupere algo nulo, se agrega esta línea para que devuelva "" tambien
                            observaciones.Add("");
                        //Nota: no se logró averiguar porque a veces observacion no era nulo directamente, sino que obtenía valores nulos por dentro
                        //por eso se agrega "" en ambos casos
                    }
                }
               
            }
            //Finalmente devuelve la lista de observaciones de cada activo de la categoría
            return observaciones;
        }

        //Requiere: vector de booleanos 
        //Modifica: lo convierte en una lista de booleanos que elimina booleanos extra
        //Retorna:  Lista de booleanos
        protected List<bool> corregirVectorBool(bool[] vec)
        {
            List<bool> nuevoVec = new List<bool>();
            int longitud = vec.Count();
            int cuenta = 0;

            while (longitud > cuenta)
            {
                if (vec[cuenta] == true)
                {
                    nuevoVec.Add(true);
                    cuenta += 2;
                }
                else
                {
                    nuevoVec.Add(false);
                    cuenta++;
                }
            }

            return nuevoVec;
        }


        //Requiere: vector de booleanos
        //Modifica: Se fija si hay algún checkbox de categoría checkeado y determina un valor a partir
        //Retorna: booleano 
        protected bool hayFilaEntera(bool[] vec)
        {
            bool ret = false;
            foreach (bool b in vec)
            {
                if (b)
                {
                    ret = true;
                    break;
                }
            }
            return ret;
        }

        //Requiere: String con el id e int de tipo de categoría 
        //Modifica: Hace consulta para recuperar los activos con la categoría y que pertenecen al id
        //Retorna:Lista de listas con información de cada activo en cada lista
        protected List<List<String>> equipoPorCategoria(int cat, String id)
        {
            List<List<String>> equipos = new List<List<String>>();

            var activos = db.PRESTAMOS.Include(i => i.ACTIVOes).SingleOrDefault(h => h.ID == id);
            // int cat = int.Parse(categoria);
            var act = from a in activos.ACTIVOes.Where(i => i.TIPO_ACTIVOID == cat)
                          //where a.ESTADO_PRESTADO == 1
                      select new { FABRICANTE = a.FABRICANTE, MODELO = a.MODELO, PLACA = a.PLACA, ID = a.ID, PRESTADO = a.ESTADO_PRESTADO };

            foreach (var a in act)
            {
                List<String> equipo = new List<String>();
                equipo.Add(a.FABRICANTE);
                equipo.Add(a.MODELO);
                equipo.Add(a.PLACA);
                equipo.Add(a.ID);
                equipo.Add(a.PRESTADO.ToString());
                equipos.Add(equipo);
            }

            return equipos;
        }

        //Requiere: diccionario con lista de listas de hileras con datos de activos
        //Modifica:  Recorre el diccionario e ingresa las placas de todos los activos dentro de él en un lista de hileras
        //Retorna: Devuelve la lista de placas de los activos
        protected List<String> listaActivos(Dictionary<String, List<List<String>>> dic)
        {
            List<String> listaActivos = new List<String>();
            foreach (KeyValuePair<String, List<List<String>>> entrada in dic)
            {
                foreach (List<String> l in entrada.Value)
                {
                    listaActivos.Add(l[2]);
                }
            }
            return listaActivos;
        }

        //Requiere: lista con las placas de los activos del préstamo y placa de un activo
        //Modifica:  Recorre dicha lista y se fija si placa es igual al elemento de la lista para recuperar la posicion de placa dentro de la lista
        //Retorna: Devuelve la posición de placa dentro de lista
        protected int indiceActivo(List<String> lista, String placa)
        {
            int indice = -1;
            for (int i = 0; i < lista.Count; i++)
            {
                if (placa == lista[i])
                {
                    indice = i;
                }
            }
            return indice;
        }

        //Requiere: String con tipo de categoría. 
        //Modifica: Hace consulta para traducir el tipo en un id
        //Retorna:devuelve el id de la categoría como un entero
        protected int traerCategoria(String tipo)
        {
            var consultaCat = from t in db.TIPOS_ACTIVOS
                              where t.NOMBRE.Equals(tipo)
                              select t.ID;

            List<String> categorias = new List<String>();

            foreach (int c in consultaCat)
            {
                categorias.Add(c.ToString());
            }
            int cat = Int32.Parse(categorias[0]);

            return cat;
        }

        // GET: PRESTAMOes
        //Requiere: Recibe 6 parámetros, el primero es la columna por la que se ordenan los datos en la tabla, el segundo, tercero, cuarto y quinto para hacer filtrado de búsqueda y el último para identificar la página en q se encuentra la tabla.
        // Modifica: Maneja el index view, la cual es la vista de consulta de revisión de solicitudes.
        //Retorna: Devuelve una tabla que se despliegará en el index de Revisión de solicitudes.
        [Authorize(Roles = "Aceptar préstamos,superadmin")]
        public ActionResult Index(string sortOrder, string currentFilter, string fechaSolicitud, string fechaRetiro, string estado, string numeroBoleta, int? page)
        {

            string username = User.Identity.GetUserName();

            var users = (from u in db.ActivosUsers select u);

            var user = users.SingleOrDefault(u => u.UserName == username);
            var cedSol = user.Id;

            //prestamos = prestamos.Where(model => model.USUARIO_SOLICITA == cedSol);

            //se identifica si alguna columna fue seleccionada como filtro para ordenar los datos despliegados
            ViewBag.currentSort = sortOrder;
            ViewBag.NumeroSortParm = String.IsNullOrEmpty(sortOrder) ? "numero_dsc" : "";

Activos-PrestamosOET/Views/PRESTAMOes/Create.cshtml
@model Activos_PrestamosOET.Models.PRESTAMO

@if (ViewBag.MensajeError != null)
{
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @ViewBag.MensajeError
    </div>
}


@{
    ViewBag.Title = "Nueva solicitud de préstamo";
}



<legend><h2>Nueva solicitud de préstamo</h2></legend>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
    if (!Modernizr.inputtypes.date) {
      $(function() {
        $( "#datepicker" ).datepicker();
      });
    }
</script>
<script>
         $.datepicker.regional['es'] = {
         closeText: 'Cerrar',
         prevText: '<Ant',
         nextText: 'Sig>',
         currentText: 'Hoy',
         monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
         monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
         dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
         dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
         dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
         weekHeader: 'Sm',
         dateFormat: 'dd/mm/yy',
         firstDay: 1,
         isRTL: false,
         showMonthAfterYear: false,
         yearSuffix: ''
         };

         $.datepicker.setDefaults($.datepicker.regional['es']);
         $(function () {
             if (!Modernizr.inputtypes.date) {
                 $('.date-picker').datepicker();
             }
         });
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $("[id$=A2]").addClass("active");
    });

    jQuery.validator.addMethod("datemustbeequalorgreaterthancurrentdate", function (value, element, param) {
        var someDate = $("#SomeDate").val();
        var today;
        var currentDate = new Date();
        var year = currentDate.getYear();
        var month = currentDate.getMonth() + 1;  // added +1 because javascript counts month from 0
        var day = currentDate.getDate();
        var hours = currentDate.getHours();
        var minutes = currentDate.getMinutes();
        var seconds = currentDate.getSeconds();

        today = month + '/' + day + '/' + year + '  ' + hours + '.' + minutes + '.' + seconds;

        if (someDate < today) {
            return false;
        }
        return true;
    });

    jQuery.validator.unobtrusive.adapters.addBool("datemustbeequalorgreaterthancurrentdate");
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="col-md-2">
                    <label class="control-label" for="inputDefault">@Html.DisplayNameFor(model => model.MOTIVO):*</label>
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.MOTIVO, new { htmlAttributes = new { @class = "form-control", @style = "70px" } })
                    @Html.ValidationMessageFor(model => model.MOTIVO, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2">
                    <label id="etiquetaFecha" class="control-label" for="inputDefault">@Html.DisplayNameFor(model => model.FECHA_RETIRO):*</label>
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.FECHA_RETIRO, new { htmlAttributes = new { @class = "form-control datepicker" } })
                    @Html.TextBox("Fecha_Inicio_Curso", null, new { @class = "form-control", @readonly = "readonly", style = "display: none" })
                    @Html.ValidationMessageFor(model => model.FECHA_RETIRO, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.TextBox("Fecha_Inicio_Curso", null, new { @class = "form-control", @readonly = "readonly", style = "display: none" })
                </div>
                <br />
                <br />
                <div class="col-md-2">
                    <label id="etiquetaFecha" class="control-label" for="inputDefault">@Html.DisplayNameFor(model => model.SIGLA_CURSO) </label>
                </div>
                <div class="col-md-4">
                    @Html.DropDownList("SIGLA_CURSO", null, "Sin Curso", htmlAttributes: new { @class = "form-control" })
                    @Html.CheckBox("asignadoACurso", false, new { @style = "display: none" })
                </div>
                <div class="col-md-2">
                    <label class="control-label" for="inputDefault">@Html.DisplayNameFor(model => model.PERIODO_USO):*</label>
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.PERIODO_USO, new { htmlAttributes = new { @min = 0, @class = "form-control", @placeholder = "Está en días." } })
                    @Html.ValidationMessageFor(model => model.PERIODO_USO, "", new { @class = "text-danger" })
                </div>
                <br/>
                <br/>
                <div class="col-lg-offset-6 col-md-2">
                    <label id="etiquetaFecha" class="control-label" for="inputDefault">Fin de préstamo:</label>
                </div>
                <div class="col-md-4">
                    @Html.TextBox("Fecha_Fin_Prestamo", null, new { @class = "form-control", @readonly = "readonly" })
                </div>
             </div>
        </div>

        <div class="form-group">
            <table class="table">
                <tr>
                    <th>
                        Equipo
                    </th>

                    <th class="col-md-4">
                        Cantidad
                    </th>
                </tr>
                @{
                    ViewData["categorias"]  = (List<String>)TempData["categorias"];
                    List<String> categorias = (List<String>)ViewData["categorias"];
                }
                @foreach (String cat in categorias)
                {
                    <tr>
                        <td>
                            @Html.Label("Categoria", @cat)
                        </td>
                        <td>
                            @Html.TextBox("Cantidad", null, new { @class = "form-control", @type = "number", @min = "0", @Value = "0" })
                            @*<input type="number" class="form-control" name="points" min="0" value="0">*@
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <br />
                    @Html.LabelFor(model => model.SOFTWARE_REQUERIDO, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SOFTWARE_REQUERIDO, new { htmlAttributes = new { @class = "form-control", @style = "40px" } })
                        @Html.ValidationMessageFor(model => model.SOFTWARE_REQUERIDO, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.OBSERVACIONES_SOLICITANTE, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OBSERVACIONES_SOLICITANTE, new { htmlAttributes = new { @class = "form-control", @style = "40px" } })
                        @Html.ValidationMessageFor(model => model.OBSERVACIONES_SOLICITANTE, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-1 col-md-10">
                        <input type="submit" value="Crear" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
                    }

<div>
    @Html.ActionLink("Historial de Solicitudes", "Historial", null, null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @*@Scripts.Render("~/bundles/jqueryval")*@

    <script type="text/javascript">


        $(document).ready(function () {
            $(".datefield").datepicker();
        });

        $("#SIGLA_CURSO").change(function () {
        var selectedValue = $("#SIGLA_CURSO").val();

        //alert(selectedText);
        if (selectedValue != "")
        {
            $("#etiquetaFecha").text("Inicio Curso:")
            $("#FECHA_RETIRO").hide();
            $("#Fecha_Inicio_Curso").show();
            $("#PERIODO_USO").prop('readonly', true);
            $("#asignadoACurso").attr('checked', true);
            $("#asignadoACurso").val(true);
            $.post('@Url.Action("obtenerFechasCurso", "PRESTAMOes")', { idCurso: selectedValue }, function (listaDatos) {
                $("#Fecha_Inicio_Curso").val(listaDatos[0]);
                $("#Fecha_Fin_Prestamo").val(listaDatos[1]);
                $("#PERIODO_USO").val(listaDatos[2]);
                //$("#FECHA_RETIRO").val(listaDatos[0]);
            });
        }
        else
        {
            $("#asignadoACurso").attr('checked', false);
            $("#etiquetaFecha").text("Inicio del préstamo:*");
            $("#FECHA_RETIRO").show();
            $("#Fecha_Inicio_Curso").hide();
            $("#Fecha_Fin_Prestamo").val("");
            $("#PERIODO_USO").val("");
            $("#PERIODO_USO").prop('readonly', false);
        }
        });


        $('#PERIODO_USO').on('input', function () {
            if ($("#PERIODO_USO").val() != "")
            {
                var fecha = new Date($("#FECHA_RETIRO").val());
                var dias = parseInt($("#PERIODO_USO").val(), 10);
                var nuevaFecha = fecha.setDate(fecha.getDate() + dias);
                var fin = fecha.getDate() + '/' + (fecha.getMonth() + 1) + '/' + fecha.getFullYear();
                $("#Fecha_Fin_Prestamo").val(fin);
            }
            else
            {
                $("#Fecha_Fin_Prestamo").val("");
            }

        });



    //   $(".datepicker").datepicker({
    //       onSelect: function () {
    //           alert("ayyy");
    //       }
    //   })
    </script>

}

Activos-PrestamosOET/Views/PRESTAMOes/Historial.cshtml
@model PagedList.IPagedList<Activos_PrestamosOET.Models.PRESTAMO>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Historial";
}

<div>
    @Html.ActionLink("Nueva Solicitud", "Create", null, null, new { @class = "btn btn-default" })
</div>

<br />

@if (ViewBag.mensajeConfirmacion != null)
{
    <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @ViewBag.mensajeConfirmacion
    </div>

}

<legend><h2>Historial de Prestamos</h2></legend>

<script type="text/javascript">
    $(document).ready(function () {
        $("[id$=A3]").addClass("active");
    });
</script>

<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();

});
</script>

@using (Html.BeginForm("Historial", "PRESTAMOes", FormMethod.Get))
{
    <div class="panel panel-default">
        <div class="panel-body">
            <fieldset>
                <label for="textArea" class="col-lg-2 control-label">Estado </label>
                <div class="col-lg-4">
                    @Html.DropDownList("estado", new SelectList(
                  new List<Object>{
                       new { text = "Todos", value = "0"},
                       new { Text = "Pendiente", Value = "1" },
                       new { Text = "Aprobada", Value = "2" },
                       new { Text = "Denegada", Value = "3" },
                       new { Text = "Abierta", Value = "4" },
                       new { Text = "Cerrada", Value = "5" },
                       new { Text = "Cancelada", Value = "6"}
                  },
                  "value",
                  "text",
                   0), new { @class = "form-control" })
                </div>
            </fieldset>


            <div class="col-md-3">
                <input type="submit" value="Buscar" class="btn btn-default" />
            </div>

        </div>
    </div>

}




<table class="table">
    <tr>
        <th>
            <label class="control-label" for="inputDefault">Número de boleta</label>
        </th>
        <th>
            <label class="control-label" for="inputDefault">Solicitud</label>
        </th>
        <th>
            <label class="control-label" for="inputDefault">Inicia</label>
        </th>
        <th>
            <label class="control-label" for="inputDefault">Finaliza</label>
        </th>
        <th>
            <label class="control-label" for="inputDefault">Estado</label>
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @switch (item.Estado)
            {
                case 1:
                <tr class="danger">
                    <td>
                        @Html.DisplayFor(modelItem => item.NUMERO_BOLETA)
                    </td>
                    <td>
                        @item.FECHA_SOLICITUD.ToShortDateString()
                        
                    </td>
                    <td>
                        @item.FECHA_RETIRO.ToShortDateString()
                    </td>
                    <td>
                        @item.FECHA_RETIRO.AddDays(item.PERIODO_USO).ToShortDateString()
                    </td>
                    <td>
                        <text>Pendiente</text>
                    </td>
                    <td>
                        <a href="@Url.Action("Detalles", new { id = item.ID })">
                                    <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Detalles"></span>
                                </a>
                    </td>
                </tr>
                    break;
                case 2:
                    <tr class="success">
                        <td>
                            @Html.DisplayFor(modelItem => item.NUMERO_BOLETA)
                        </td>
                        <td>
                            @item.FECHA_SOLICITUD.ToShortDateString()
                        </td>
                        <td>
                            @item.FECHA_RETIRO.ToShortDateString()
                        </td>
                        <td>
                            @item.FECHA_RETIRO.AddDays(item.PERIODO_USO).ToShortDateString()
                        </td>
                        <td>
                            <text>Aceptada</text>
                        </td>
                        <td>
                            <a href="@Url.Action("Detalles", new { id = item.ID })">
                                <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Detalles"></span>
                            </a>
                        </td>
                    </tr>
                    break;
                case 3:
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NUMERO_BOLETA)
                        </td>
                        <td>
                            @item.FECHA_SOLICITUD.ToShortDateString()
                        </td>
                        <td>
                            @item.FECHA_RETIRO.ToShortDateString()
                        </td>
                        <td>
                            @item.FECHA_RETIRO.AddDays(item.PERIODO_USO).ToShortDateString()
                        </td>
                        <td>
                            <text>Denegada</text>
                        </td>
                        <td>
                            <a href="@Url.Action("Detalles", new { id = item.ID })">
                                <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Detalles"></span>
                            </a>
                        </td>
                    </tr>
                    break;
                case 4:
                    <tr class="warning">
                        <td>
                            @Html.DisplayFor(modelItem => item.NUMERO_BOLETA)
                        </td>
                        <td>
                            @item.FECHA_SOLICITUD.ToShortDateString()
                        </td>
                        <td>
                            @item.FECHA_RETIRO.ToShortDateString()
                        </td>
                        <td>
                            @item.FECHA_RETIRO.AddDays(item.PERIODO_USO).ToShortDateString()
                        </td>
                        <td>
                            <text>Abierta</text>
                        </td>
                        <td>
                            <a href="@Url.Action("Detalles", new { id = item.ID })">
                                <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Detalles"></span>
                            </a>
                        </td>
                    </tr>
                    break;
                case 5:
                    <tr class="info">
                        <td>
                            @Html.DisplayFor(modelItem => item.NUMERO_BOLETA)
                        </td>
                        <td>
                            @item.FECHA_SOLICITUD.ToShortDateString()
                        </td>
                        <td>
                            @item.FECHA_RETIRO.ToShortDateString()
                        </td>
                        <td>
                            @item.FECHA_RETIRO.AddDays(item.PERIODO_USO).ToShortDateString()
                        </td>
                        <td>
                            <text>Cerrada</text>
                        </td>
                        <td>
                            <a href="@Url.Action("Detalles", new { id = item.ID })">
                                <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Detalles"></span>
                            </a>
                        </td>
                    </tr>
                    break;
                case 6:
                    <tr class="active">
                        <td>
                            @Html.DisplayFor(modelItem => item.NUMERO_BOLETA)
                        </td>
                        <td>
                            @item.FECHA_SOLICITUD.ToShortDateString()
                        </td>
                        <td>
                            @item.FECHA_RETIRO.ToShortDateString()
                        </td>
                        <td>
                            @item.FECHA_RETIRO.AddDays(item.PERIODO_USO).ToShortDateString()
                        </td>
                        <td>
                            <text>Cancelada</text>
                        </td>
                        <td>
                            <a href="@Url.Action("Detalles", new { id = item.ID })">
                                <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Detalles"></span>
                            </a>
                        </td>
                    </tr>
                    break;
            }
            </tr>
    }

</table>

<div class="col-md-offset-9 col-md-12">

    <button type="button" data-trigger="focus" class="btn btn-default" data-container="body" data-toggle="popover" data-placement="top" data-html="true" data-content="Rojo: Pendiente <br>Verde: Aceptado <br>Blanco: Denegado <br>Amarillo: Abierta <br>Azul: Cerrada <br>Gris: Cancelada" data-original-title="" title="¿Qué significan los colores?">¿Qué significan los colores?</button>

    <br />
</div>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Historial",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, estado = ViewBag.estado }))