Activos-PrestamosOET/Controllers/ActivosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using SendGrid;
using System.Web;
using System.Web.Mvc;
using Activos_PrestamosOET.Models;
using PagedList;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Configuration;
using iTextSharp.text.pdf;
using iTextSharp.text;
using System.IO;

namespace Activos_PrestamosOET.Controllers
{
    [Authorize]
    public class ActivosController : Controller
    {
        private PrestamosEntities db = new PrestamosEntities();
        private TransaccionesController controladora_transaccion = new TransaccionesController();

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActivosController() { }

        public ActivosController(ApplicationUserManager userManager)
        {
            this.UserManager = userManager;
        }

        [Authorize(Roles = "Ingresar activos, Desechar activos, Editar activos, Aceptar préstamos, superadmin")]
        // GET: Inventario
        public ActionResult Inventario(string orden, int? pagina, string busqueda)
        {
            ViewBag.OrdenActual = orden;
            ViewBag.Compania = String.IsNullOrEmpty(orden) ? "compania_desc" : "";
            ViewBag.Estacion = (orden == "estacion_asc") ? "estacion_desc" : "estacion_asc";
            ViewBag.Tipo = (orden == "tipo_asc") ? "tipo_desc" : "tipo_asc";
            ViewBag.Responsable = (orden == "responsable_asc") ? "responsable_desc" : "responsable_asc";
            ViewBag.Descripcion = (orden == "descrip_asc") ? "descrip_desc" : "descrip_asc";


            //se obtiene el usuario loggeado
            var user = UserManager.FindById(User.Identity.GetUserId());
            Boolean isAdmin = User.IsInRole("superadmin") ? true : false;
            IQueryable<ACTIVO> aCTIVOS = ACTIVO.busquedaSimple(busqueda, user.EstacionID, isAdmin);

            switch (orden)
            {
                case "compania_desc":
                    aCTIVOS = aCTIVOS.OrderByDescending(a => a.V_ANFITRIONA.SIGLAS);
                    break;
                case "estacion_asc":
                    aCTIVOS = aCTIVOS.OrderBy(a => a.V_ESTACION.SIGLAS);
                    break;
                case "estacion_desc":
                    aCTIVOS = aCTIVOS.OrderByDescending(a => a.V_ESTACION.SIGLAS);
                    break;
                case "tipo_asc":
                    aCTIVOS = aCTIVOS.OrderBy(a => a.TIPOS_ACTIVOS.NOMBRE);
                    break;
                case "tipo_desc":
                    aCTIVOS = aCTIVOS.OrderByDescending(a => a.TIPOS_ACTIVOS.NOMBRE);
                    break;
                case "responsable_asc":
                    aCTIVOS = aCTIVOS.OrderBy(a => a.V_EMPLEADOS.NOMBRE);
                    break;
                case "responsable_desc":
                    aCTIVOS = aCTIVOS.OrderByDescending(a => a.V_EMPLEADOS.NOMBRE);
                    break;
                case "descrip_desc":
                    aCTIVOS = aCTIVOS.OrderByDescending(a => a.DESCRIPCION);
                    break;
                case "descrip_asc":
                    aCTIVOS = aCTIVOS.OrderBy(a => a.DESCRIPCION);
                    break;
                default:
                    aCTIVOS = aCTIVOS.OrderBy(a => a.V_ANFITRIONA.SIGLAS);
                    break;
            }

            int tamano_pagina = 20;
            int num_pagina = (pagina ?? 1);
            return View(aCTIVOS.ToPagedList(num_pagina, tamano_pagina));
        }

        // POST que genera un PDF con codigos de barras
        [HttpPost]
        public ActionResult GenerarPDFCodigoBarras(string[] marcados, int codigo_seleccionado = 0)
        {
            string nombre_archivo = "Códigos " + DateTime.Now.ToString(@"MM\/dd\/yyyy h\:mm tt");
            marcados = marcados.Where(val => val != "false").ToArray();
            Response.Clear();
            Response.ContentType = "application/pdf";
            Response.AddHeader("content-disposition", "attachment;filename=" + nombre_archivo + ".pdf");
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.BinaryWrite(CrearPDF(marcados, codigo_seleccionado));
            Response.End();
            return RedirectToAction("Inventario");
        }

        /**
         * Metodo que se encarga de generar un PDF ya sean con codigos QR o de Barras dependiendo de lo que haya elegido el usuario.
         **/
        private byte[] CrearPDF(string[] datos, int tipo)
        {
            byte[] bPDF = null;

            MemoryStream ms = new MemoryStream();
            Document doc = new Document(PageSize.A4, 25, 25, 25, 25);
            PdfWriter writer = PdfWriter.GetInstance(doc, ms);
            doc.Open();
            switch (tipo)
            { //Escoger tipo de PDF
                case 1:
                    doc.Add(CodigoQR(datos, 6));
                    break;
                default:
                    doc.Add(Codigo39(datos, writer, 6));
                    break;
            }
            doc.Close();
            bPDF = ms.ToArray();
            return bPDF;
        }

        /**
         * Metodo que genera un PDF con codigos QR
         * **/
        private PdfPTable CodigoQR(string[] datos, int codigos_por_fila)
        {
            PdfPTable table = new PdfPTable(codigos_por_fila);
            table.WidthPercentage = 100;
            //****Se agregan elementos 
            for (int i = 0; i < datos.Length; i++)
            {
                BarcodeQRCode bc = new BarcodeQRCode(datos[i], 1, 1, null);
                PdfPCell cell = new PdfPCell(table.DefaultCell);
                cell.AddElement(new Chunk("OET - " + datos[i]));
                cell.AddElement(bc.GetImage());
                table.AddCell(cell);
            }
            table.CompleteRow();
            return table;
        }

        /**
         * Metodo que genera un PDF con codigos de barras.
         * **/
        private PdfPTable Codigo39(string[] datos, PdfWriter writer, int codigos_por_fila)
        {
            PdfPTable table = new PdfPTable(codigos_por_fila);
            table.WidthPercentage = 100;
            //****Se agregan elementos 
            for (int i = 0; i < datos.Length; i++)
            {
                Barcode39 bc = new Barcode39();
                PdfContentByte cb = new PdfContentByte(writer);
                bc.Code = datos[i];
                bc.N = 3;
                bc.X = 1;
                bc.AltText = "OET - " + datos[i].ToString();
                PdfPCell cell = new PdfPCell(table.DefaultCell);
                cell.AddElement(bc.CreateImageWithBarcode(cb, null, null));
                table.AddCell(cell);
            }
            table.CompleteRow();
            return table;
        }




        // GET: Activos
        [Authorize(Roles = "Ingresar activos, Desechar activos, Editar activos, Aceptar préstamos, superadmin")]
        public ActionResult Index(string orden, string filtro, string busqueda, string V_PROVEEDORIDPROVEEDOR, string TIPO_ACTIVOID, string V_ANFITRIONAID, string TIPO_TRANSACCIONID, string ESTADO_ACTIVOID, string V_ESTACIONID, string fecha_antes, string fecha_despues, string usuario, string fabricante, int? pagina)
        {

            ViewBag.OrdenActual = orden;
            ViewBag.Compania = String.IsNullOrEmpty(orden) ? "compania_desc" : "";
            ViewBag.Estacion = (orden == "estacion_asc") ? "estacion_desc" : "estacion_asc";
            ViewBag.Tipo = (orden == "tipo_asc") ? "tipo_desc" : "tipo_asc";
            ViewBag.Responsable = (orden == "responsable_asc") ? "responsable_desc" : "responsable_asc";
            ViewBag.Descripcion = (orden == "descrip_asc") ? "descrip_desc" : "descrip_asc";
            //se obtiene el usuario loggeado
            var user = UserManager.FindById(User.Identity.GetUserId());
            Boolean isAdmin = User.IsInRole("superadmin") ? true : false;
            // Paginación
            if (busqueda != null)
            {
                pagina = 1;
            }
            else
            {
                busqueda = filtro;
            }

            ViewBag.FiltroActual = busqueda;

            // Busqueda con base en los parametros que ingresa el usuario
            #region Busqueda simple
            IQueryable<ACTIVO> aCTIVOS = ACTIVO.busquedaSimple(busqueda, user.EstacionID, isAdmin); //OJO
            #endregion

            #region Busqueda avanzada

            // Para las opciones de busqueda avanzada
            ViewBag.TIPO_TRANSACCIONID = new SelectList(db.TIPOS_TRANSACCIONES, "ID", "NOMBRE");
            ViewBag.TIPO_ACTIVOID = new SelectList(db.TIPOS_ACTIVOS, "ID", "NOMBRE");
            ViewBag.V_PROVEEDORIDPROVEEDOR = new SelectList(db.V_PROVEEDOR, "IDPROVEEDOR", "NOMBRE");
            ViewBag.V_ANFITRIONAID = new SelectList(db.V_ANFITRIONA, "ID", "NOMBRE");
            ViewBag.ESTADO_ACTIVOID = new SelectList(db.ESTADOS_ACTIVOS, "ID", "NOMBRE");
            ViewBag.V_ESTACIONID = new SelectList(db.V_ESTACION, "ID", "NOMBRE");

            Dictionary<string, string> params_busqueda = new Dictionary<string, string>();

            params_busqueda.Add("proveedor", V_PROVEEDORIDPROVEEDOR);
            params_busqueda.Add("tipo_activo", TIPO_ACTIVOID);
            params_busqueda.Add("anfitriona", V_ANFITRIONAID);
            params_busqueda.Add("tipo_transaccion", TIPO_TRANSACCIONID);
            params_busqueda.Add("fecha_antes", fecha_antes);
            params_busqueda.Add("fecha_despues", fecha_despues);
            params_busqueda.Add("usuario", usuario);

Activos-PrestamosOET/Views/Activos/Asignar.cshtml
@model Activos_PrestamosOET.Models.ACTIVO

@{
    ViewBag.Title = "Asignar";
}
<div class="row">
    <div class="col-xs-12">
        <br />
        @Html.ActionLink("Regresar", "Index")
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <h2>Modificar el estado del activo.</h2>
        <hr />
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-sm-6 col-xs-12">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-12 col-sm-4">
                        @Html.LabelFor(model => model.PLACA, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-xs-12 col-sm-8">
                        @Html.EditorFor(model => model.PLACA, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control", @rows = "3" } })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12 col-sm-4">
                        @Html.LabelFor(model => model.DESCRIPCION, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-xs-12 col-sm-8">
                        @Html.EditorFor(model => model.DESCRIPCION, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control", @rows = "3" } })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12 col-sm-4">
                        @Html.LabelFor(model => model.INICIO_SERVICIO, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-sm-8 col-xs-12">
                        @Html.EditorFor(model => model.INICIO_SERVICIO, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.INICIO_SERVICIO, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12 col-sm-4">
                        @Html.LabelFor(model => model.ESTADO_ACTIVOID, "Estado", htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-sm-8 col-xs-12">
                        @Html.DropDownList("ESTADO_ACTIVOID", null, "-- Seleccione el estado del activo --", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ESTADO_ACTIVOID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div id="info-asignacion" style="display:none;">
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-4">
                            @Html.LabelFor(model => model.V_ESTACIONID, "Estación", htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-xs-12 col-sm-8">
                            @Html.DropDownList("V_ESTACIONID", null,"-- Seleccione una estación --", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.V_ESTACIONID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-4">
                            @Html.LabelFor(model => model.V_EMPLEADOSIDEMPLEADO, "Responsable", htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-sm-8 col-xs-12">
                            @Html.DropDownList("V_EMPLEADOSIDEMPLEADO", null,"-- Seleccione un responsable --", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.V_EMPLEADOSIDEMPLEADO, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-4">
                            @Html.LabelFor(model => model.CENTRO_DE_COSTOId, "Centro de costo", htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-sm-8 col-xs-12">
                            @Html.DropDownList("CENTRO_DE_COSTOId", null, "-- Seleccione un centro de costo --", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CENTRO_DE_COSTOId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-12 col-sm-3">
                        @Html.LabelFor(model => model.COMENTARIO, htmlAttributes: new { @class = "control-label" })
                    </div>
                    <div class="col-sm-9 col-xs-12">
                        @Html.EditorFor(model => model.COMENTARIO, new { htmlAttributes = new { @class = "form-control", @rows = "5" } })
                        @Html.ValidationMessageFor(model => model.COMENTARIO, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <span class="pull-right">
                <input id='boton_prueba'type="submit" value="Guardar" class="btn btn-default" />

                <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
                <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet" />
                <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
                <script type="text/javascript">
                $(document).ready(function() {
                    toastr.options.timeOut = 10000; // 10s                    
                    $('#boton_prueba').click(function () {      
                        toastr.success('Se enviará un correo electrónico al usuario correspondiente si se le asigna un activo.', 'INFORMACIÓN');                       
                    });
                });
                </script>


            </span>
        </div>
    </div>
}

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

        $("#activos").addClass("active");

        $(function () {
            $('#info-asignacion').css('display', ($('#ESTADO_ACTIVOID option:selected').text() == 'Asignado') ? 'block' : 'none');
            $('#ESTADO_ACTIVOID').on('change', function () {
                $('#info-asignacion').css('display', ($('#ESTADO_ACTIVOID option:selected').text() == 'Asignado') ? 'block' : 'none');
            });
            $('#V_ESTACIONID').on('change', function () {
                var estacion_id = $('#V_ESTACIONID').val();
                var lista_empleados = $('#V_EMPLEADOSIDEMPLEADO');
                lista_empleados.empty();
                lista_empleados.append("<option value=''>-- Seleccione un responsable --</option>");
                $.ajax({
                    url: "@Url.Content("~/Activos/RefrescarUsuarios")",
                    data: {id_estacion: estacion_id },
                    dataType: "json",
                    success: function (data) {
                        lista_empleados.empty();
                        lista_empleados.append("<option value=''>-- Seleccione un responsable --</option>");
                        $.each(data, function (index, option_data) {
                            lista_empleados.append("<option value='" + option_data.IDEMPLEADO + "'>" + option_data.NOMBRE + "</option>");
                        });
                    }
                });
            });
        });
    </script>
}

Activos-PrestamosOET/Views/Activos/Inventario.cshtml
@model PagedList.IPagedList<Activos_PrestamosOET.Models.ACTIVO>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Inventario y códigos de barras";
}
<div class="row">
    <div class="col-xs-12">
        <h2>Control de inventario y códigos de barras</h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        @using (Html.BeginForm("Inventario", "Activos", FormMethod.Get))
        {
            <div class="input-group">
                @Html.Editor("busqueda", ViewBag.FiltroActual as string, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese su búsqueda de activos" } })
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default" title="Buscar"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                </span>
            </div>
        }
        <div class="pull-left">
            <p>
                <small>
                    @Html.ActionLink("Limpiar búsqueda", "Index", "UsersAdmin", new { @title = "Eliminar los filtros de la búsqueda" })
                </small>
            </p>
        </div>
        <br />
    </div>
</div>
@using (Html.BeginForm("GenerarPDFCodigoBarras", "Activos", FormMethod.Post))
{

    <div class="row">
        <div class="col-xs-12 col-sm-10 col-sm-offset-1">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>@Html.ActionLink("Compañía", "Inventario", new { orden = ViewBag.Compania }, new { @title = "Ordenar por la compañía" })</th>
                            <th>@Html.ActionLink("Estación", "Inventario", new { orden = ViewBag.Estacion }, new { @title = "Ordenar por la estación" })</th>
                            <th>@Html.ActionLink("Tipo", "Inventario", new { orden = ViewBag.Tipo }, new { @title = "Ordenar por el tipo" })</th>
                            <th>@Html.ActionLink("Responsable", "Inventario", new { orden = ViewBag.Responsable }, new { @title = "Ordenar por el responsable" })</th>
                            <th>
                                @Html.ActionLink("Descripción", "Inventario", new { orden = ViewBag.Descripcion }, new { @title = "Ordenar por la descripción del activo" })
                            </th>
                            <th class="text-center">Acciones</th>
                            <th class="text-center">Generar código</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.DESECHADO)
                            {
                                <tr class="danger">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.V_ANFITRIONA.SIGLAS)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.V_ESTACION.SIGLAS)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TIPOS_ACTIVOS.NOMBRE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.V_EMPLEADOS.NOMBRE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DESCRIPCION)
                                    </td>
                                    <td class="text-center">
                                        <a href="@Url.Action("Details", new { id = item.ID })">
                                            <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Detalles"></span>
                                        </a>
                                    </td>
                                    <td></td>
                                </tr>

                            }
                            else
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.V_ANFITRIONA.SIGLAS)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.V_ESTACION.SIGLAS)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TIPOS_ACTIVOS.NOMBRE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.V_EMPLEADOS.NOMBRE)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DESCRIPCION)
                                    </td>
                                    <td class="text-center">
                                        <a href="@Url.Action("Details", new { id = item.ID })">
                                            <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Detalles"></span>
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        @Html.CheckBox("marcados", new { @value = item.PLACA, @class = "seleccionado"})
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-10 col-sm-offset-1">
            <div class="pull-left">
                <small><span class="text-muted">Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount</span></small>
                @Html.PagedListPager(Model, pagina => Url.Action("Inventario", new { pagina, orden = ViewBag.OrdenActual }))
            </div>
            <div class="pull-right">
                <select class="selectpicker" data-style="btn-primary" name="codigo_seleccionado">
                    <option value="0">Formato Code39</option>
                    <option value="1">Formato QR</option>
                </select>
                <button type="submit" class="btn btn-default" id="btn_submit" title="Generar código de barras de activos seleccionados" disabled>Generar códigos</button>
            </div>
        </div>
    </div>
}

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $("#activos").addClass("active");
        $(".seleccionado").change(function () {
            var numberOfChecked = $('input:checkbox:checked').length;
            if (numberOfChecked > 0) {
                $('#btn_submit').attr('disabled', false);
            } else {
                $('#btn_submit').attr('disabled', true);
            }
        });
    </script>
}