Activos-PrestamosOET/Controllers/UsersAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Activos_PrestamosOET.Models;
using PagedList;

namespace Activos_PrestamosOET.Controllers
{
    [Authorize(Roles = "superadmin")]
    public class UsersAdminController : Controller
    {

        private PrestamosEntities db = new PrestamosEntities();

        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        public async Task<ActionResult> Index(string orden, int? pagina, string busqueda)
        {
            ViewBag.OrdenActual = orden;
            ViewBag.Nombre = String.IsNullOrEmpty(orden) ? "nombre_desc" : "";
            ViewBag.Correo = (orden == "correo_asc") ? "correo_desc" : "correo_asc";

            var usuarios = await UserManager.Users.ToListAsync();

            #region Busqueda de usuarios
            if (!String.IsNullOrEmpty(busqueda))
                usuarios = usuarios.Where(usr => usr.FullName.Contains(busqueda) || usr.Email.Contains(busqueda)).ToList();
            #endregion

            switch (orden)
            {
                case "nombre_desc":
                    usuarios = usuarios.OrderByDescending(emp => emp.FullName).ToList();
                    break;
                case "correo_asc":
                    usuarios = usuarios.OrderBy(emp => emp.Email).ToList();
                    break;
                case "correo_desc":
                    usuarios = usuarios.OrderByDescending(emp => emp.Email).ToList();
                    break;
                default:
                    usuarios = usuarios.OrderBy(emp => emp.FullName).ToList();
                    break;
            }
            int tamano_pagina = 20;
            int num_pagina = (pagina ?? 1);
            return View(usuarios.ToPagedList(num_pagina, tamano_pagina));
        }

        public struct TransaccionesConActivo
        {
            public string activo_id;
            public DateTime transaccion_fecha;
            public string activo_descripcion;
            public string numero_de_placa;
            public string transaccion_descripcion;
            public string activo_nuevo_estado;
            public string activo_categoria;
            public bool activo_desechado;
            public TransaccionesConActivo(string id, DateTime fecha, string descripcion, string trans_desc, string placa, bool desechado, string nuevo_estado, string act_cat)
            {
                activo_id = id;
                transaccion_fecha = fecha;
                activo_descripcion = descripcion;
                transaccion_descripcion = trans_desc;
                numero_de_placa = placa;
                activo_desechado = desechado;
                activo_nuevo_estado = nuevo_estado;
                activo_categoria = act_cat;
            }
        }
        //
        // GET: /Users/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);
            var estaciones = db.V_ESTACION.ToList();
            ViewBag.Estacion = estaciones.Where(e => e.ID.Equals(user.EstacionID)).ToList()[0].NOMBRE;
            List<TRANSACCION> listaTransacciones = db.TRANSACCIONES.Where(e => e.RESPONSABLE.Equals(user.Email)).ToList();
            List<TransaccionesConActivo> transacciones_listas = new List<TransaccionesConActivo>();
            foreach(TRANSACCION item in listaTransacciones)
            {
                ACTIVO activo = db.ACTIVOS.Find(item.ACTIVOID);
                TIPOS_ACTIVOS tipo = db.TIPOS_ACTIVOS.Find(activo.TIPO_ACTIVOID);
                transacciones_listas.Add(new TransaccionesConActivo(item.ACTIVOID, item.FECHA, activo.DESCRIPCION, item.DESCRIPCION, activo.PLACA, activo.DESECHADO, item.ESTADO, tipo.NOMBRE));
            }
            ViewBag.Transacciones = transacciones_listas;

            return View(user);
        }

        //
        // GET: /Users/Create
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            ViewBag.EstacionID = new SelectList(db.V_ESTACION, "ID", "NOMBRE");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = userViewModel.Email,
                    Email = userViewModel.Email,
                    // Add the Address Info:
                    Nombre = userViewModel.Nombre,
                    Apellidos = userViewModel.Apellidos,
                    Cedula = userViewModel.Cedula,
                    EstacionID = userViewModel.EstacionID
                };



                // Then create:
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.EstacionID = new SelectList(db.V_ESTACION, "ID", "NOMBRE");
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }


                    //enviar correo de confirmacion al nuevo usuario
                    string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    string cuerpo_del_mensaje = "Bienvenido al sistema de Activos de la Organizacicón de Estudios Tropicales. " +
                                                "Se creó una cuenta asociada a este correo con los siguientes roles: Préstamos -" + string.Join(" - ", selectedRoles)+". " +
                                                "Por favor confirme su correo ingresando a este <a href=\"" + callbackUrl + "\">enlace</a>. " +
                                                "Si no solicitó una cuenta por favor ignore este correo.";

                    await UserManager.SendEmailAsync(user.Id, "Confirme su inscripción", cuerpo_del_mensaje);

                    ViewBag.Message = "Se ha enviado un correo de confirmacion a la direccion del nuevo usuario. El nuevo usuario debe confirmar su dirección de correo" +
                                        " para poder ingresar al sistema.";

                    return View("Info");
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    ViewBag.EstacionID = new SelectList(db.V_ESTACION, "ID", "NOMBRE");
                    return View();

                }
                //return RedirectToAction("Index");
            }
            ViewBag.EstacionID = new SelectList(db.V_ESTACION, "ID", "NOMBRE");
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }


        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);
            var editUser = new EditUserViewModel();
            editUser.Id = user.Id;
            editUser.Email = user.Email;
            editUser.Nombre = user.Nombre;
            editUser.Apellidos = user.Apellidos;
            editUser.Cedula = user.Cedula;
            editUser.EstacionID = user.EstacionID;
            editUser.RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
            {
                Selected = userRoles.Contains(x.Name),

Activos-PrestamosOET/Views/UsersAdmin/Create.cshtml
@model Activos_PrestamosOET.Models.RegisterViewModel
@{
    ViewBag.Title = "Crear Usuario";
}
<div class="row">
    <div class="col-xs-12">
        <br />
        @Html.ActionLink("Regresar", "Index")
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <h2>Crear un nuevo usuario</h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="col-xs-12 col-sm-4 col-sm-offset-4">
                    @Html.ValidationSummary("", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="form-group">
                        <div class="col-xs-12 col-lg-3">
                            @Html.LabelFor(m => m.Nombre, new { @class = "control-label required" })
                        </div>
                        <div class="col-xs-12 col-lg-9">
                            @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="form-group">
                        <div class="col-xs-12 col-lg-3">
                            @Html.LabelFor(m => m.Apellidos, new { @class = "control-label required" })
                        </div>
                        <div class="col-xs-12 col-lg-9">
                            @Html.TextBoxFor(m => m.Apellidos, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="form-group">
                        <div class="col-xs-12 col-lg-3">
                            @Html.LabelFor(m => m.Cedula, new { @class = "control-label required" })
                        </div>
                        <div class="col-xs-12 col-lg-9">
                            @Html.TextBoxFor(m => m.Cedula, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="form-group">
                        <div class="col-xs-12 col-lg-3">
                            @Html.LabelFor(m => m.Email, new { @class = "control-label required" })
                        </div>
                        <div class="col-xs-12 col-lg-9">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="form-group">
                        <div class="col-xs-12 col-lg-3">
                            @Html.LabelFor(model => model.EstacionID, "Estación", htmlAttributes: new { @class = "control-label required" })
                        </div>
                        <div class="col-xs-12 col-lg-9">
                            @Html.DropDownList("EstacionID", null, "-- Seleccione una estación --", htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EstacionID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="form-group">
                        <div class="col-xs-12 col-lg-3">
                            <label class="control-label required">Roles</label>
                        </div>
                        <div class="col-xs-12 col-lg-9">
                            <div class="dropdown">
                                <button class="form-control dropdown-toggle" type="button" id="drop_roles" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="text-align:left;">
                                    -- Seleccione los roles -- <span class="pull-right"> <span class="caret"></span></span>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="drop_roles" style="padding:5px 10px;">
                                    @foreach (var item in (SelectList)ViewBag.RoleId)
                                    {
                                        <li>
                                            @if (item.Value.Equals("Solicitar préstamos"))
                                            {<input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" checked="checked" disabled="disabled" /> }
                                            else
                                            { <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" /> }
                                            @Html.Label(item.Value, new { @class = "control-label" })
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="form-group">
                        <div class="col-xs-12 col-lg-3">
                            @Html.LabelFor(m => m.Password, new { @class = "control-label required" })
                        </div>
                        <div class="col-xs-12 col-lg-9">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="form-group">
                        <div class="col-xs-12 col-lg-3">
                            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "control-label required" })
                        </div>
                        <div class="col-xs-12 col-lg-9">
                            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-12">
                    <p class="text-danger"><small>(*) Campos obligatorios</small></p>
                    <div class="pull-right">
                        <input type="submit" class="btn btn-default" value="Crear usuario" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval"))
    <script type="text/javascript">
        $("#opciones_avanzadas").addClass("active");
        $("form").submit(function () {
            $("input").removeAttr("disabled");
        });
    </script>
}

Activos-PrestamosOET/Views/UsersAdmin/Delete.cshtml
@model Activos_PrestamosOET.Models.ApplicationUser
@{
    ViewBag.Title = "Eliminar usuario";
}
<div class="row">
    <div class="col-xs-12">
        <br />
        @Html.ActionLink("Regresar", "Index")
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <h2>@ViewBag.Title</h2>
        <h4>¿Esta seguro que desea eliminar a este usuario?</h4>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-5 col-sm-offset-1">
        <div class="row">
            <div class="col-xs-12">
                <h4>Datos del usuario</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                @Html.LabelFor(model => model.FullName)
            </div>
            <div class="col-xs-8">
                <p>@Html.DisplayFor(model => model.FullName)</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                <label for="correo" class="control-label">Correo</label>
            </div>
            <div class="col-xs-8">
                <p id="correo">@Html.DisplayFor(model => model.Email)</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                <label class="control-label" for="estacion">Estación</label>
            </div>
            <div class="col-xs-8">
                <p id="estacion">@ViewBag.Estacion</p>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-5">
        <div class="row">
            <div class="col-xs-12">
                <h4>Roles del usuario</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                @if (ViewBag.RoleNames.Count == 0)
                {
                    <p>No se le han asignado roles al usuario</p>
                }
                else
                {
                    <ul>
                        @foreach (var item in ViewBag.RoleNames)
                {
                            <li>
                                <p>@item</p>
                            </li>
                        }
                    </ul>
                }
            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="pull-right">
                <div class="form-group">
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-primary" })
                    <input type="submit" value="Borrar" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $("#opciones_avanzadas").addClass("active");
    </script>
}

Activos-PrestamosOET/Views/UsersAdmin/Details.cshtml
@model Activos_PrestamosOET.Models.ApplicationUser
@{
    ViewBag.Title = "Detalles de usuario";
}
<div class="row">
    <div class="col-xs-12">
        <br />
        @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Regresar", "Index")
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <h2>@ViewBag.Title</h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-5 col-sm-offset-1">
        <div class="row">
            <div class="col-xs-12">
                <h4>Datos personales</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                @Html.LabelFor(model => model.FullName)
            </div>
            <div class="col-xs-8">
                <p>@Html.DisplayFor(model => model.FullName)</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                @Html.LabelFor(model => model.Email)
            </div>
            <div class="col-xs-8">
                <p>@Html.DisplayFor(model => model.Email)</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                @Html.LabelFor(model => model.Cedula)
            </div>
            <div class="col-xs-8">
                <p>@Html.DisplayFor(model => model.Cedula)</p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                <label class="control-label" for="estacion">Estación</label>
            </div>
            <div class="col-xs-8">
                <p id="estacion">@ViewBag.Estacion</p>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-5">
        <div class="row">
            <div class="col-xs-12">
                <h4>Roles asignados</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                @if (ViewBag.RoleNames.Count == 0)
                {
                    <p>No se le han asignado roles al usuario</p>
                }
                else
                {
                    <ul>
                        @foreach (var item in ViewBag.RoleNames)
                {
                            <li>
                                <p>@item</p>
                            </li>
                        }
                    </ul>
                }
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            Fecha
                        </th>
                        <th>
                            Categoría de activo
                        </th>
                        <th>
                            Número de placa
                        </th>
                        <th>
                            Descripción del activo
                        </th>
                        <th>
                            Nuevo estado
                        </th>
                        <th>
                            Descripción de la transacción
                        </th>
                        <th class="text-center">
                            Ver
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ViewBag.Transacciones)
                    {
                        <!--activo_desechado = desechado;-->
                        if (item.activo_desechado)
                        {
                            <tr class="danger">
                                <td>
                                    @item.transaccion_fecha
                                </td>
                                <td>
                                    @item.activo_categoria
                                </td>
                                <td>
                                    @item.numero_de_placa
                                </td>
                                <td>
                                    @item.activo_descripcion
                                </td>
                                <td>
                                    @item.activo_nuevo_estado
                                </td>
                                <td>
                                    @item.transaccion_descripcion
                                </td>
                                <td class="text-center">
                                    <a href="@Url.Action("Details", "Activos", new { id = item.activo_id })">
                                        <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Ver activo"></span>
                                    </a>
                                </td>
                            </tr>
                        }
                        else
                        {
                            <tr>
                                <td>
                                    @item.transaccion_fecha
                                </td>
                                <td>
                                    @item.activo_categoria
                                </td>
                                <td>
                                    @item.numero_de_placa
                                </td>
                                <td>
                                    @item.activo_descripcion
                                </td>
                                <td>
                                    @item.activo_nuevo_estado
                                </td>
                                <td>
                                    @item.transaccion_descripcion
                                </td>
                                <td class="text-center">
                                    <a href="@Url.Action("Details", "Activos", new { id = item.activo_id })">
                                        <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Ver activo"></span>
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $("#opciones_avanzadas").addClass("active");
    </script>
}

Activos-PrestamosOET/Views/UsersAdmin/Index.cshtml
@model PagedList.IPagedList<Activos_PrestamosOET.Models.ApplicationUser>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Usuarios del sistema";
}

<div class="row">
    <div class="col-xs-12">
        <h2>Usuarios del sistema</h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        @using (Html.BeginForm("Index", "UsersAdmin", FormMethod.Get))
        {
            <div class="input-group">
                @Html.Editor("busqueda", ViewBag.FiltroActual as string, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese su búsqueda de usuarios" } })
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default" title="Buscar"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                </span>
            </div>
        }
        <div class="pull-left">
            <p>
                <small>
                    @Html.ActionLink("Limpiar búsqueda", "Index", "UsersAdmin", new { @title = "Eliminar los filtros de la búsqueda" })
                </small>
            </p>
        </div>
        <br />
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            @Html.ActionLink("Nombre", "Index", new { orden = ViewBag.Nombre}, new { @title="Ordenar por el nombre"})
                        </th>
                        <th>
                            @Html.ActionLink("Correo electrónico", "Index", new { orden = ViewBag.Correo }, new { @title = "Ordenar por el correo electrónico" })
                        </th>
                        <th colspan="3" class="text-center">
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.FullName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td class="text-center">
                                <a href="@Url.Action("Edit", new {id= item.Id})">
                                    <span class="glyphicon glyphicon-edit text-warning" aria-hidden="true" title="Editar"></span>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="@Url.Action("Details", new { id = item.Id })">
                                    <span class="glyphicon glyphicon-eye-open text-info" aria-hidden="true" title="Detalles"></span>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="@Url.Action("Delete", new { id = item.Id })">
                                    <span class="glyphicon glyphicon-erase text-danger" aria-hidden="true" title="Eliminar"></span>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <div class="pull-left">
            <small><span class="text-muted">Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount</span></small>
            @Html.PagedListPager(Model, pagina => Url.Action("Index", new { pagina, orden = ViewBag.OrdenActual }))
        </div>
        <div class="pull-right">
            @Html.ActionLink("Crear nuevo usuario", "Create", new object { }, new { @class = "btn btn-default" })
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $("#opciones_avanzadas").addClass("active");
    </script>
}